### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/website#37]
Hi there 

https://code.gitea.io/

I click on the code and get directed to a page with a few lines and .. no Code.

I see there is a link on the left side and suggest to link https://github.com/go-gitea directly in this central text.

**Comment by strk** [comment]
@ShalokShalom I find 3 links on the left, for the 3 projects for which there's Code.
This is Go, btw, which means you can download the code using `go get code.gitea.io/gitea` for gitea itself, or `go get code.gitea.io/<other>` for other gitea projects (those linked on that page).

Maybe you want to provide a pull request to include the info above in that page ?

**Comment by tboerger** [comment]
All 3 available projects are linking to the GitHub repository, so you know where to find the code. As @strk already said these pages are at all used to provide the custom go import path, e.g. `go get code.gitea.io/gitea`

**Comment by ShalokShalom** [comment]
Yeah, i know that the link is on the left side. 

@strk Are you sure, that this page is here in this repo?

**Comment by tboerger** [comment]
The pages for code.gitea.io are generated out of https://github.com/go-gitea/redirects
