### ISSUE TITLE
A list of differences to gogs

### ISSUE THREAD

**Issue by mqus** [go-gitea/website#40]
I just set up a new server and am considering migrating to gitea from gogs. I searched for a short page/text comparing gogs and gitea feature-wise and didn't find anything so far on your website. I'm aware of the reason of the fork and I noticed that there is a list of features in the docs but comparing multiple pages of bulletpoints really isn't something which should be done by visitors.

It would really help me (and propably other people considering a move) if there was a reasonably up-to-date list of properties which are unique to gitea, maybe also a list of features that are only available in gogs.

(If there already exists such a list, make it more discoverable, please! )

Thank you!

**Comment by lunny** [comment]
I think it's difficult to compare Gitea with Gogs since both have new features since Gitea forked from Gogs. But I think the most different thing is Gitea has many maintainers but Gogs has one.

**Comment by tboerger** [comment]
I have to say I dislike this idea because it will never stay up 2 date. Better have lesser information than wrong information.

**Comment by Chouchen** [comment]
Well, I'm using Gogs since a long time and I don't know if the migration is worth the cost of time. 
Don't take me wrong but one maintainer against many is not a good enough reason to me. One can know its own software more than many, no offense.

If there are really good new features in Gitea that Gogs doesn't have, I'm interested.

**Comment by lafriks** [comment]
@Chouchen LDAP user sync, CI status API and display in commit list, more granular access to each repository unit - these were features important to me but there are so many changes in both projects that it is really hard to keep track. As there are some features that are also differently implemented in each project.

**Comment by ptman** [comment]
@lunny mentioned:

- GPG verification
- Units Permission Controls

Also mentioned were:

- 2FA (which gogs later introduced)
- Broader API (?)
- OpenID

**Comment by lunny** [comment]
* Status API
* LDAP Sync
* Batch issues operation
* OAuth Login

**Comment by tboerger** [comment]
So what do we want to do with this report?

**Comment by lunny** [comment]
A reason for why should we convert Gogs to Gitea? :smile:

**Comment by lafriks** [comment]
Probably leave it open while we create docs comparing them as this question raises very often otherwise

**Comment by ShalokShalom** [comment]
Yes

**Comment by justin13888** [comment]
Probably best if you try hosting both of them and comparing it yourself

**Comment by techknowlogick** [comment]
Closing this as this page now exists at https://docs.gitea.io/en-us/comparison/

**Comment by ShalokShalom** [comment]
Very impressive
