### ISSUE TITLE
Me poor eyes

### ISSUE THREAD

**Issue by laplix** [go-gitea/website#50]
Hi folks,

Would it be possible to improve the contrast in the menu please?

I understand that the hot thing for designers today is to write very light text on a lighter background or the inverse, very dark text or darker background.

The problem is: Designers are super humans with 250%  eyesight or they are like me and zoom 200 or 300% to see what they do....

But, we the users,  are just normal folks with usually less than 100% eyesight. As of me, I am 60+ years old, and probably have between 70~80% (going on cataract...). Even with new glasses, I still have difficulties reading the gitea.io docs menu.

A bit more contrast would help a lot.

(Well, maybe I could go with Stylus and style your site to my liking, but I would rather code my stuff and use your stuff as is...)

Thank you. for this beautiful project and I hope you find the time to do this.
Louis

**Comment by tboerger** [comment]
Hi @laplix, I can totally understand that and it should be possible to give parts of the website or the docs a better contrast. Are you refering only to the main top navigation? or also to the sub navigation on the left side we got on the docs?

**Comment by ShalokShalom** [comment]
Darker theme?

**Comment by laplix** [comment]
I am very, very sorry.  I totally forgot about this issue. 
Today, I had an idea and came here to see if it had already been suggested and landed on my own issue
So, I just went through gitea.io, and found that everything looks sharp. So, a **BIG THANK YOU**
Well... maybe a bit more contrast for the links? Current color is kind of light green (#1abc9c) which is a bit light... 
I don't come here often (on gitea.io). Mostly because I use gitea on my home machine to host my code and issues until I am ready to publish... well, one day...

You can close this issue. Your site is perfectly legible (I'll manage the links...). Again, thank you for Gitea.  We can manage our code without having to publish it immediately and  using it is a real pleasure..

**Comment by lunny** [comment]
@laplix just like @ShalokShalom said. When v1.6 landed(current v1.6-rc1), you can enable dark theme. You can find the config options on https://docs.gitea.io/en-us/config-cheat-sheet/ [ui] DEFAULT_THEME, default is gitea and you can change it to arc-green. Of course, if you are setting up a fresh installation, you can chose one on installation page.

**Comment by ShalokShalom** [comment]
Thanks for the theme ^-^

There is also https://github.com/darkreader/darkreader for other pages :)
