### ISSUE TITLE
API link doesn't appear to work

### ISSUE THREAD

**Issue by klauern** [go-gitea/website#57]
I attempted to look at the underlying API to see if I could write some tool against it, but the link to the API page doesn't seem to show anything resembling an API at all.  It actually looks like a demo.

![image](https://user-images.githubusercontent.com/4735/33042826-cbfcd538-ce08-11e7-838e-41e70a80738d.png)

Links to https://try.gitea.io/swagger, but that shows this:

![image](https://user-images.githubusercontent.com/4735/33042844-de304334-ce08-11e7-9c85-ab574bb2d1b8.png)

**Comment by lafriks** [comment]
@go-gitea/owners go-gitea/docs updates are not published after PR has been merged

**Comment by lunny** [comment]
recent PR is 4 months ago, It seems no PR to change that? see https://drone.gitea.io/go-gitea/docs.

**Comment by lafriks** [comment]
@lunny There was PR #10 that was merged 10 days ago to fix that

**Comment by lunny** [comment]
Yes, but no drone action on https://drone.gitea.io/go-gitea/website. Something wrong on drone maybe.

**Comment by lafriks** [comment]
@lunny same is also for docs, merged PR but no action on drone

**Comment by lunny** [comment]
This should not be a problem any more.
