### ISSUE TITLE
https://try.gitea.io/ is down?

### ISSUE THREAD

**Issue by treedust** [go-gitea/website#65]
![cantbereached](https://user-images.githubusercontent.com/16553346/37680435-7eda38b4-2c49-11e8-9d2c-759eef14f460.png)

Is something I came across when looking at gitea.io

**Comment by lafriks** [comment]
It is know, try.gitea.io is being moved to larger DO instance because of regular issues with disk space

**Comment by treedust** [comment]
Thank you.

**Comment by strk** [comment]
Duplicate of #58

**Comment by bkcsoft** [comment]
It's up :)
