### ISSUE TITLE
SSL/TLS invalid certificate

### ISSUE THREAD

**Issue by ostaszewskik** [go-gitea/website#81]
After entering the page https://gitea.io/:

gitea.io uses an invalid security certificate. The certificate expired on 28 August 2018, 18:33:27 GMT+2. The current time is 28 August 2018, 19:00. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by iamhansen** [comment]
The certificate is expired, if you really want to see the website and are using chrome, type in "thisisunsafe" to bypass the error.

**Comment by techknowlogick** [comment]
ping @tboerger

**Comment by tboerger** [comment]
We had initial reached the limit of new Let's Encrypt certificates after moving to Netlify hosting. After that I simply forgot to enable Let's Encrypt again ;)
