### ISSUE TITLE
Comparison with Atlassian Bitbucket Server

### ISSUE THREAD

**Issue by ymartin59** [go-gitea/website#85]
About: https://docs.gitea.io/en-us/comparison/
From my point of view, you should rename "BitBucket" column as "Bitbucket.org" but I am not sure that it the "expected target" as all other alternative are self-hosting on-premise products.
Probably you may create an additional column to compare to "Atlassian Bitbucket Server" - I may help about it: https://www.atlassian.com/software/bitbucket/features

**Comment by lunny** [comment]
@ymartin59 Please send pull request to help us to fix that.

**Comment by lunny** [comment]
You have to send a PR on https://github.com/go-gitea/gitea
